#Topic Web
kafka:
  bootstrap-servers: kafka-0:9092,kafka-1:9092,kafka-2:9092 #,localhost:29092,localhost:29093,localhost:29094  #kafka-0:9091 #localhost:29092,kafka-0:9091

jwt-key:
  link: "http://authorization-server:9000/jwks"