#Post Server
datasource:
  url: jdbc:postgresql://postgres:5432/postsdb # ##jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
  username: forum # ##${POSTGRES_USER}
  password: ForumPassword # ##${POSTGRES_PASSWORD}
  dialect: org.hibernate.dialect.PostgreSQLDialect
#hibernate:
#  ddl-auto: create    # create
kafka:
  bootstrap-servers: kafka:9092