#Post Server
# prod
datasource:
  url: jdbc:postgresql://postgres:5432/postsdb
  username: forum
  password: ForumPassword
  dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  ddl-auto: update
kafka:
  bootstrap-servers: kafka:9092