#Post Server DEV
datasource:
  url: jdbc:postgresql://localhost:5432/postsdb
  username: forum
  password: ForumPassword
  dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  ddl-auto: update
kafka:
  bootstrap-servers: localhost:9092