server:
  application:
    name: post-server
spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  main: ## need to disable tomcat port 8080
    web-application-type: none
  kafka:
    bootstrap-servers: ${kafka.bootstrap-servers}
    consumer: 
      auto-offset-reset: earliest
      group-id: post-server
  liquibase:
    changeLog: "classpath:db/changelog.sql"
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: ${hibernate.ddl-auto}
        dialect: ${datasource.dialect}
    show-sql: true

kafka:
  topic:
    product:
      request: post-req-topic
      reply: post-req-reply-topic
  request-reply:
    timeout-ms: 10000
product:
  topic:
    request:
      numPartitions: 5
logging:
  level:
    root: info
springdoc:
  api-docs:
    path: /postsweb/v3/api-docs
  swagger-ui:
    path: /postsweb/
    url: /postsweb/v3/api-docs
