#Post Server
# prod
datasource:
  url: jdbc:postgresql://postgres-post:5432/postsdb
  username: forum
  password: ForumPassword
  dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  ddl-auto: update
kafka:
  bootstrap-servers: kafka-0:9092,kafka-1:9092,kafka-2:9092