
spring:
  datasource:
    username: forum
    password: ForumPassword
    url: jdbc:postgresql://localhost:5433/topicsdb
    driver-class-name: org.postgresql.Driver
    driverClassName: org.postgresql.Driver

    hikari:
      auto-commit: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
#    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: post-server
  liquibase:
    changeLog: "classpath:db/changelog-test.sql"
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: create
        auto-commit: true
    show-sql: true
    hibernate:
      autocommit: true
      auto-commit: true
kafka:
  topic:
    product:
      request: post-req-topic
      reply: post-req-reply-topic
  request-reply:
    timeout-ms: 10000
product:
  topic:
    request:
      numPartitions: 2
logging:
  level:
    root: info