server:
  port: 8090

app.host-url: /

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9000
springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: Order Service
        url: http://localhost:18071/topicsweb/v3/api-docs
#      - name: Inventory Service
#        url: http://inventory-service/v3/api-docs
# ##############springdoc.swagger-ui.path: /doc