server:
  application:
    name: topic-server
spring:
  datasource:
    url: ${datasource1.url}
    username: ${datasource1.username}
    password: ${datasource1.password}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: ${kafka1.bootstrap-servers}
    consumer: 
      auto-offset-reset: earliest
      group-id: topic-server
  liquibase:
    changeLog: "classpath:db/changelog.sql"
  main: ## need to disable tomcat port 8080
    web-application-type: none
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#        hbm2ddl:
#          auto: ${hibernate1.ddl-auto} # #create-drop
#        dialect: ${hibernate1.dialect}
    show-sql: true
#    database-platform: ${hibernate1.dialect}

kafka:
  topic:
    product:
      request: topic-req-topic
      reply: topic-req-reply-topic
  request-reply:
    timeout-ms: 10000
product:
  topic:
    request:
      numPartitions: 1
logging:
  level:
    root: info
