server:
  port: 8090

app.host-url: /

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9000
#
springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: Topic Service
        url: http://localhost:18071/topicsweb/v3/api-docs
      - name: Post Service
        url: http://localhost:18091/postsweb/v3/api-docs
      - name: Directory Service
        url: http://localhost:18081/directoriesweb/v3/api-docs