# Authorization server
application.localhost-path: localhost
datasource1:
  url: jdbc:postgresql://localhost:5432/users_repo # ##jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
  username: forum # ##${POSTGRES_USER}
  password: ForumPassword # ##${POSTGRES_PASSWORD}
hibernate1:
  ddl-auto: update    # create
#show-sql: true

auth-provider:
  issuer-uri: "http://localhost:9000"
auth-server:
  get-jwk-link: "http://localhost:9000/jwks"
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${application.localhost-path}:9000