server:
  port: 9000

logging:
  level:
    #root: TRACE
    org.springframework.security: trace

spring:
  jpa:
    hibernate:
      ddl-auto: ${hibernate1.ddl-auto}    # create
    show-sql: true
  sql:
    init:
      mode: always    #  spring.datasource.initialization-mode: always

  h2:
    console:
      enabled: true


 #   console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: ${datasource1.url} #jdbc:postgresql://localhost:5432/users_repo
    username: ${datasource1.username} #forum
    password: ${datasource1.password} #ForumPassword

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/jwks2.json
          issuer-uri: http://localhost:9000

security:
  oauth2:
    resource:
      jwt:
#        key-value: http://localhost:9000/jwk.json
        key-uri: http://localhost:9000/jwk.json
#      jwk:
#        key-set-uri: http://localhost:9000/jwk.json
#    resourceserver:
#      jwt:
#        jwk-set-uri: http://localhost:9000/jwks.json