#Directory Server
datasource:
  url: jdbc:postgresql://postgres-directory:5432/directoriesdb
  username: forum
  password: ForumPassword
  dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  ddl-auto: update


kafka:
  bootstrap-servers: kafka-0:9092,kafka-1:9092,kafka-2:9092