#Topic Server

datasource1:
  url: jdbc:postgresql://postgres-topic:5432/topicsdb
  username: forum
  password: ForumPassword
hibernate1:
  ddl-auto: create
  dialect: org.hibernate.dialect.PostgreSQLDialect
kafka1:
  bootstrap-servers: kafka-0:9092,kafka-1:9092,kafka-2:9092

