#Topic server

datasource1:
  url: jdbc:postgresql://localhost:5432/topicsdb
  username: forum
  password: ForumPassword
hibernate1:
  ddl-auto: update
  dialect: org.hibernate.dialect.PostgreSQLDialect
kafka1:
  bootstrap-servers: localhost:9092
