#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    registerWithEureka: false
#    fetchRegistry: false
#    server:
#      waitTimeInMsWhenSyncEmpty: 0
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  # from: https://github.com/spring-cloud-samples/eureka/blob/master/src/main/resources/application.yml
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
#    response-cache-update-interval-ms: 5000
#
#management.endpoints.web.exposure.include: "*"
#
## if prod is active
#spring.config.activate.on-profile: prod
#eureka.instance.hostname: eureka


#
server:
  port: 8761
spring:
  application:
    name: eureka
#  config:
#    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false        # in 9 partition was false
    service-url:
      defaultZone: http://eureka-server:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  eureka-username: u
  eureka-password: p




#server:
#  port: 8761
#
#app:
#  eureka-username: u
#  eureka-password: p
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  # from: https://github.com/spring-cloud-samples/eureka/blob/master/src/main/resources/application.yml
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
#    response-cache-update-interval-ms: 5000
#
#management.endpoints.web.exposure.include: "*"