#Directory Server
datasource:
  url: jdbc:postgresql://postgres-directory:5432/directoriesdb # ##jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
  username: forum # ##${POSTGRES_USER}
  password: ForumPassword # ##${POSTGRES_PASSWORD}
hibernate:
  ddl-auto: create    # create

kafka:
  bootstrap-servers: kafka:9092