#Directory Server
datasource:
  url: jdbc:postgresql://localhost:5432/directoriesdb # ##jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
  username: forum # ##${POSTGRES_USER}
  password: ForumPassword # ##${POSTGRES_PASSWORD}
hibernate:
  ddl-auto: update    # create

kafka:
  bootstrap-servers: localhost:9092