# Authorization server
application.localhost-path: authorization-server
datasource1:
  url: jdbc:postgresql://postgres-users_repo:5432/users_repo # ##jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
  username: forum # ##${POSTGRES_USER}
  password: ForumPassword # ##${POSTGRES_PASSWORD}
hibernate1:
  ddl-auto: update    # create

auth-provider:
  issuer-uri: http://${application.localhost-path}:9000
auth-server:
  get-jwk-link: http://${application.localhost-path}:9000/jwks

eureka:
  defaultZoneUrl: http://u:p@eureka-server:8761/eureka/