DROP TABLE IF EXISTS USERS;
create table users
(
    id               bigint generated by default as identity
        primary key,
    creation_date    timestamp,
    email            varchar(255)
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    last_change_date timestamp,
    login            varchar(255)
        constraint ukow0gan20590jrb00upg3va2fn
            unique,
    password         varchar(255),
    user_role        varchar(255)
);

alter table users
    owner to forum;

insert into users(login, email, password, user_role)
values ('user', '1@gmail', '{noop}password', 'USER');
insert into users(login, email, password, user_role)
values ('admin', '2@gmail', '{noop}password', 'ADMIN');
